-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 14:13:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BBDD_IPO
-- -----------------------------------------------------
-- Base de datos creada para la práctica de Interacción Persona Ordenador I.
-- 20/12/2017
DROP SCHEMA IF EXISTS `BBDD_IPO` ;

-- -----------------------------------------------------
-- Schema BBDD_IPO
--
-- Base de datos creada para la práctica de Interacción Persona Ordenador I.
-- 20/12/2017
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BBDD_IPO` DEFAULT CHARACTER SET utf8 ;
USE `BBDD_IPO` ;

-- -----------------------------------------------------
-- Table `BBDD_IPO`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BBDD_IPO`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `BBDD_IPO`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Email` VARCHAR(60) NULL,
  `Contraseña` VARCHAR(16) NULL,
  `Telefono` INT NULL,
  `RolPrincipal` VARCHAR(45) NULL,
  `Conocientos` VARCHAR(140) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BBDD_IPO`.`Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BBDD_IPO`.`Proyectos` ;

CREATE TABLE IF NOT EXISTS `BBDD_IPO`.`Proyectos` (
  `IdProyecto` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaCreacion` DATE NULL,
  `Responsable` INT NULL,
  `Descripcion` VARCHAR(240) NULL,
  PRIMARY KEY (`IdProyecto`),
  INDEX `fgResponsble_idx` (`Responsable` ASC),
  CONSTRAINT `fgResponsble`
    FOREIGN KEY (`Responsable`)
    REFERENCES `BBDD_IPO`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BBDD_IPO`.`Tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BBDD_IPO`.`Tareas` ;

CREATE TABLE IF NOT EXISTS `BBDD_IPO`.`Tareas` (
  `idTareas` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaIni` DATE NULL,
  `FechaFin` DATE NULL,
  `Estado` VARCHAR(45) NULL,
  `Prioridad` INT NULL,
  `Encargado` INT NULL,
  `Comentarios` VARCHAR(2040) NULL,
  PRIMARY KEY (`idTareas`),
  INDEX `fgEncargado_idx` (`Encargado` ASC),
  CONSTRAINT `fgEncargado`
    FOREIGN KEY (`Encargado`)
    REFERENCES `BBDD_IPO`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BBDD_IPO`.`ProyecTareaUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BBDD_IPO`.`ProyecTareaUser` ;

CREATE TABLE IF NOT EXISTS `BBDD_IPO`.`ProyecTareaUser` (
  `idProyecto` INT NOT NULL,
  `idTarea` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  UNIQUE INDEX `idProyecTareaUser_UNIQUE` (`idProyecto` ASC),
  UNIQUE INDEX `ProyecTareaUsercol_UNIQUE` (`idTarea` ASC),
  UNIQUE INDEX `ProyecTareaUsercol1_UNIQUE` (`idUsuario` ASC),
  CONSTRAINT `fgProyec`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `BBDD_IPO`.`Proyectos` (`IdProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fgTarea`
    FOREIGN KEY (`idTarea`)
    REFERENCES `BBDD_IPO`.`Tareas` (`idTareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fgUser`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BBDD_IPO`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
